python_crash_course/python_crash_course_3/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # 注册用户的APP url
    path("users/", include("users.urls")),
    # 在项目的文件夹中再创建一个 urls，用于管理APP的路由（urls）
    path("", include("learning_logs.urls")),
]

python_crash_course/python_crash_course_3/learning_logs/urls.py
# 定义 APP leading_logs 的URL
from django.urls import path

# 从上级页面引入视图
from . import views

app_name = "learning_logs"
urlpatterns = [
    # 主页
    # 1参: 路径
    # 2参: 匹配路径后，调用的函数
    # 3参: 这个URL匹配规则，叫啥
    path("", views.index, name="index"),
    path("topics/", views.topics, name="topics"),
    # 特定主题的详细页面
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    # 用于添加新主题的页面
    path("new_topic/", views.new_topic, name="new_topic"),
    # 用于添加新条目的页面
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    # 用于编辑条目的页面
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
]

python_crash_course/python_crash_course_3/users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    # 默认身份验证的UR: 如 login/logout
    path("", include("django.contrib.auth.urls")),
    # 注册页面
    path("register/", views.register, name="register"),
]

python_crash_course/python_crash_course_3/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    # 用户学习的主题
    # django支持哪些类型，请参考该文档
    # https://docs.djangoproject.com/en/4.2/ref/models/fields/
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # 该函数返回的值，为最终Topic模块的展示
    def __str__(self) -> str:
        return self.text


# 学到的有关具体某个主题的知识
class Entry(models.Model):
    # 设置外键，并指定在主表(Topic)数据删除触发的时候，进行级联删除
    # 这是一种一对多关系中常见的策略，比如一个主题下有多个知识点，如果这个主题被删除了
    # 那么这些知识点也就不存在了（级联删除）
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    # meta类用于管理模型的额外信息，这里的设置，让 django 在需要时用 entries 表示多个
    # 条目，而不是 entrys
    class Meta:
        # plural: adj. 复数的;多元的;复数形式的;多样的
        # n. (名词或动词的)复数，复数形式
        verbose_name_plural = "entries"

    def __str__(self) -> str:
        return f"{self.text[:50]}..."

    # 该函数返回的值，为最终Topic模块的展示
    def __str__(self) -> str:
        return self.text

python_crash_course/python_crash_course_3/users/models.py
from django.db import models

# Create your models here.

python_crash_course/python_crash_course_3/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = {"text"}
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = {"text"}
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

python_crash_course/python_crash_course_3/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

# 这个应该是python的神奇路径标志，表示当前文件夹下的 models 文件
from .models import Topic
from .forms import TopicForm, EntryForm, Entry


# Create your views here.
def index(request):
    # 学习笔记主页
    # request: 请求对象
    # learning_logs/index.html: 用于创建页面的模板
    # 这个模板的实际位置在 templates 文件夹下
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    # 显示所有主题: 象棋、攀岩
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


# 作为views，实际上。返回具体视图和模板，并组装数据。
# 在运行topic函数前，先下运行 login_required
@login_required
def topic(request, topic_id):
    # 显示单个主题以及所有的条目
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        # raise 抛出异常
        raise Http404
    # date_added前面的-号，表示按降序排列
    entries = topic.entry_set.order_by("date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    # 添加新主题
    if request.method != "POST":
        # 未提交数据，创建新表单
        form = TopicForm()
    else:
        # POST提交数据，对数据进行处理
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("learning_logs:topics")

    # 显示空表单或指出表单数据无效
    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def new_entry(request, topic_id):
    # 在特定主题中添加新条目
    topic = Topic.objects.get(id=topic_id)
    if request.method != "POST":
        # 未提交数据，创建新表单
        form = EntryForm()
    else:
        # POST提交数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            # commit = False 表示产生结果，但是不提交到数据库
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            # 再保存到数据库
            new_entry.save()
            return redirect("learning_logs:topic", topic_id=topic_id)

    # 显示空表单或指出表单数据无效
    context = {"topic": topic, "form": form}
    # 1参:要重定向的视图 2参:带往视图的参数
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    # 编辑既有条目
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        # raise 抛出异常
        raise Http404

    if request.method != "POST":
        # 初次请求
        form = EntryForm(instance=entry)
    else:
        # POST提交数据，处理数据
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learnng_logs:topic", topic_id=topic.id)

    # 显示空表单或指出表单数据无效
    context = {"entry": entry, "topic": topic, "form": form}
    # 1参:要重定向的视图 2参:带往视图的参数
    return render(request, "learning_logs/edit_entry.html", context)

python_crash_course/python_crash_course_3/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    # 注册新用户
    if request.method != "POST":
        # 未提交数据，创建新表单
        form = UserCreationForm()
    else:
        # POST提交数据，对数据进行处理
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重新定向到主页
            login(request, new_user)
            return redirect("learning_logs:index")

    # 显示空表单或指出表单数据无效
    context = {"form": form}
    return render(request, "registration/register.html", context)

python_crash_course/python_crash_course_3/learning_logs/templates/learning_logs/base.html
<!-- @format -->

{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      cntent="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Learning Log</title>
    {% bootstrap_css %} {% bootstrap_javascript jquery='full' %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a
        class="navbar-brand"
        href="{% url 'learning_logs:index' %}"
        >Learning Log</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarCollapse"
        aria-controls="navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="collapse navbar-collapse"
        id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url 'learning_logs:topics' %}"
              >Topics</a
            >
          </li>
        </ul>
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello,{{ user.username }}</span>
          </li>
          {% else %}
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url 'users:register' %}"
              >Register</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url 'users:login' %}"
              >Log in</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main
      role="main"
      class="container">
      <div class="pb-2 mb-2 border-bottom">{% block page_header %}{% endblock page_header %}</div>
      <div>{% block content %}{% endblock %}</div>
    </main>
  </body>
</html>

python_crash_course/python_crash_course_3/learning_logs/templates/learning_logs/edit_entry.html
<!-- @format -->
{% extends 'learning_logs/base.html' %} {% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit Entry:</p>
<form
  action="{% url 'learning_logs:edit_entry' topic.id %}"
  method="post">
  {% csrf_token %} {{ form.as_p }}
  <button name="submit">Save Changes</button>
</form>
{% endblock content %}

python_crash_course/python_crash_course_3/learning_logs/templates/learning_logs/index.html
<!-- @format -->
{% extends 'learning_logs/base.html' %} {% block page_header %}
<div class="jumbotron">
  <h1 class="display-3">Track Your learning</h1>
  <p class="lead">
    Make your own Learning Log, and keep a list of the topics you're learning about, Whenerver you learn something new
    about a topic , make a entry summarizing what you've learned
  </p>
  <a
    class="btn btn-lg btn-primary"
    href="{% url 'users:register' %}"
    role="button"
    >Register &raquo;</a
  >
</div>
{% endblock page_header %}

python_crash_course/python_crash_course_3/learning_logs/templates/learning_logs/new_entry.html
<!-- @format -->
{% extends 'learning_logs/base.html' %} {% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Add a new Entry</p>
<form
  action="{% url 'learning_logs:new_entry' topic.id %}"
  method="post">
  {% csrf_token %} {{ form.as_p }}
  <button name="submit">Add entry</button>
</form>
{% endblock content %}

python_crash_course/python_crash_course_3/learning_logs/templates/learning_logs/new_topic.html
<!-- @format -->
{% extends 'learning_logs/base.html' %} {% block content %}
<p>Add a new Topic</p>
<form
  action="{% url 'learning_logs:new_topic' %}"
  method="post">
  {% csrf_token %} {{ form.as_p }}
  <button name="submit">Add topic</button>
</form>
{% endblock content %}

python_crash_course/python_crash_course_3/learning_logs/templates/learning_logs/topic.html
<!-- @format -->
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h3>{{topic}}</h3>
{% endblock page_header %} {% block content %}
<p><a href="{% url 'learning_logs:new_entry' topic.id %}"> Add new entry</a></p>

{% for entry in entries %}
<div class="card mb-3">
  {% comment %} 这里要特别注意， date:'M d, Y H:i' ,如果在date: 后多加一个空格，就会报错 {% endcomment %}
  <h4 class="card-header">
    {{ entry.date_added|date:'M d, Y H:i' }}
    <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
  </h4>
  <div class="card-body">{{ entry.text|linebreaks }}</div>
</div>
{% empty %}
<p>There are no entries for this topic yet.</p>
{% endfor %} {% endblock content %}

python_crash_course/python_crash_course_3/learning_logs/templates/learning_logs/topics.html
<!-- @format -->
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>Topics</h1>
{% endblock page_header %} {% block content %}
<ul>
  {% comment %} topics 是从render函数的三参中传递而来 {% endcomment %} {% for topic in topics %} {% comment %}
  作为变量，被如此直接插入到模板，和一般的代码有所不同 {% endcomment %}
  <li>
    <h3>
      <a href="{% url 'learning_logs:topic' topic.id %}"> {{topic}} </a>
    </h3>
  </li>
  {% comment %} 模板标签，表示为空的时候，Django需要怎么办 {% endcomment %} {% empty %}
  <li><h3>No Topic have been added yet</h3></li>
  {% endfor %}
</ul>
<h3>
  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
</h3>
{% endblock content %}